source("http://bioconductor.org/biocLite.R")
biocLite("DESeq2")
library("DESeq2")
??DESeq2
help(DESeq2)
dm409.df = read.table("/home/jab112/2017_macalpine_chr_remod/data/mrc1/DM409/DM409_brdu_coverage_2500bp_win.txt", sep = "\t", header = T, row.names = 1)
head(dm409.df)
dm410.df = read.table("/home/jab112/2017_macalpine_chr_remod/data/mrc1/DM410/DM410_brdu_coverage_2500bp_win.txt", sep = "\t", header = T, row.names = 1)
dm391.df = read.table("/home/jab112/2017_macalpine_chr_remod/data/mrc1_isw1_isw2/DM391/DM391_brdu_coverage_2500bp_win.txt", sep = "\t", header = T, row.names = 1)
dm414.df = read.table("/home/jab112/2017_macalpine_chr_remod/data/mrc1_isw1_isw2/DM414/DM414_brdu_coverage_2500bp_win.txt", sep = "\t", header = T, row.names = 1)
cts.m = matrix(0, nrow = nrow(dm409.df), ncol = 4)
rownames(cts.m) = rownames(dm409.df)
cts.m[,1] = round(dm409.df$Norm_Counts)
cts.m[,2] = round(dm410.df$Norm_Counts)
cts.m[,3] = round(dm391.df$Norm_Counts)
cts.m[,4] = round(dm414.df$Norm_Counts)
colnames(cts.m) = c("ctrl1", "ctrl2", "mutant1", "mutant2")
design.df = data.frame(mutation = c("ctrl", "ctrl", "mutant", "mutant"))
rownames(design.df) = colnames(cts.m)
design.df
dds = DESeqDataSetFromMatrix(countData = cts.m, colData = design.df, design = ~ mutation)
dds
dds2 = DESeq(dds)
resultsName(dds2)
resultsNames(dds2)
res = results(dds2, name = "mrc1 vs mrc1_isw1_isw2")
res = results(dds2)
res
result.df = as.data.frame(res)
head(result.df)
head(result.df[order(result.df$padj),])
head(cts.m)
rownames(head(result.df[order(result.df$padj),]))
cts.m[rownames(head(result.df[order(result.df$padj),])),]
savehistory("~/2017_macalpine_chr_remod/src/R/run_DESeq2.R")
